---
# let the user join only the groups that exist on the remote host

#- name: get existing groups on host
- name: get a list of existing groups
  shell: "getent group | cut -f 1 -d':' | tr '\\n' ','"
  register: existing_groups
  changed_when: False

- name: put user in the existing groups
  user:
    name: "{{ item.0.name }}"
    append: yes
    groups: "{{ item.1 | default('') }}"
  with_subelements:
    - users
    - groups
  when:
    item.1 is defined
    and user_state == "present"
    and item.1 in existing_groups.stdout
